### ISSUE TITLE
AzureOpenAIClient with DefaultOpenAIClient() throws intermittent 401s

### ISSUE THREAD

**Issue by cdwaddell** [openai/openai-dotnet#115]
I have the following setup as a Singleton using dependency injection:

```
new AzureOpenAIClient(
    new Uri(endpoint),
    new DefaultAzureCredential(),
    new AzureOpenAIClientOptions(ServiceVersion.V2024_06_01)
);
```

I then inject this into my application and use this code to chat:

```
var chatClient = _openAIClient.GetChatClient(deploymentName);
var response = await chatClient.CompleteChatAsync(messages, options);
```

Intermittently, this call returns a 401. It seems to happen every 30 seconds or so and lasts for 30 seconds, then it goes away. Is there an issue with token management? FYI, this code worked fine before v2.0.

**Comment by joseharriaga** [comment]
Thank you for reaching out, @cdwaddell  ! This repo corresponds to the [OpenAI library](https://www.nuget.org/packages/OpenAI/AbsoluteLatest). Since you're using the `AzureOpenAIClient` with the `DefaultAzureCredential` from the [Azure.AI.OpenAI library](https://www.nuget.org/packages/Azure.AI.OpenAI), could you file this issue in the Azure repo instead? Here's a link: 🔗 https://github.com/Azure/azure-sdk-for-net

Thank you!

**Comment by cdwaddell** [comment]
Thanks, here is the bug if anyone needs it:

https://github.com/Azure/azure-sdk-for-net/issues/44910
