### ISSUE TITLE
How can I download a file from OpenAI api

### ISSUE THREAD

**Issue by RezaRahmatzadeh** [openai/openai-dotnet#126]
How can I enable file downloads from the OpenAI API using the OpenAI NuGet package? I’m currently using version 2.0.0-beta.1.

While the platform indicates this isn’t feasible, I’ve come across code snippets for making HTTP requests to the OpenAI API to retrieve files.

**Comment by RezaRahmatzadeh** [comment]
> Thank you for reaching out, @RezaRahmatzadeh ! What kind of files are you referring to and for what purpose? If you're thinking of the Files API as documented [here](https://platform.openai.com/docs/api-reference/files/retrieve-contents), you can download previously uploaded files using the `FileClient`'s `DownloadFile` method.

I am referring to files that are generated by OpenAI in response to user requests, similar to how ChatGPT provides downloadable links for files (e.g., Excel files) in the ChatGPT UI. Is it possible to generate and provide such downloadable files via the OpenAI API?

**Comment by joseharriaga** [comment]
Yes, that is possible! You can use the `FileClient`'s `DownloadFile` method and pass the ID of the file you want to download. 

You might find the following example useful: 🔗 [Example01_RetrievalAugmentedGeneration.cs](https://github.com/openai/openai-dotnet/blob/main/examples/Assistants/Example01_RetrievalAugmentedGeneration.cs#L134). Here, the assistant can generate an image, which can be downloaded using the method I mentioned above so that it can be displayed in the UI.

**Comment by RezaRahmatzadeh** [comment]
> Yes, that is possible! You can use the `FileClient`'s `DownloadFile` method and pass the ID of the file you want to download.
> 
> You might find the following example useful: 🔗 [Example01_RetrievalAugmentedGeneration.cs](https://github.com/openai/openai-dotnet/blob/main/examples/Assistants/Example01_RetrievalAugmentedGeneration.cs#L134). Here, the assistant can generate an image, which can be downloaded using the method I mentioned above so that it can be displayed in the UI.

Great, thanks, I'll try.
