### ISSUE TITLE
Assistant streaming run throwing exception.

### ISSUE THREAD

**Issue by AndrawsYaqoob01** [openai/openai-dotnet#210]
### Confirm this is not an issue with the OpenAI Python Library

- [ ] This is not an issue with the OpenAI Python Library

### Confirm this is not an issue with the underlying OpenAI API

- [X] This is not an issue with the OpenAI API

### Confirm this is not an issue with Azure OpenAI

- [X] This is not an issue with Azure OpenAI

### Describe the bug

Assistant streaming run is throwing exception when trying to access a function call in RequiredActionUpdate.

Exception is:
System.ClientModel.ClientResultException: 'HTTP 400 (invalid_request_error: )
Thread THREAD_ID already has an active run RUN_ID

### To Reproduce

1. Run example Example02b_FunctionCallingStreaming

### OS

winOS

### .NET version

.NET 8.0

### Library version

2.0.0-beta.11

**Comment by trrwilson** [comment]
@AndrawsYaqoob01, thank you for contacting us and drawing attention to this problem in the sample!

This appears to stem from a pattern change introduced with #128 -- because `RequiredActionUpdate` now is now derived from `RunUpdate`, the sample's existing check (`RunUpdate` first, then `RequiredActionUpdate`) now never processes the needed logic in `RequiredActionUpdate`.

We'll get this sample updated ASAP; the quick fix is to just swap the order of the two blocks to:

```csharp
                if (update is RequiredActionUpdate requiredActionUpdate)
                {
                    if (requiredActionUpdate.FunctionName == getTemperatureTool.FunctionName)
                    {
                        outputsToSubmit.Add(new ToolOutput(requiredActionUpdate.ToolCallId, "57"));
                    }
                    else if (requiredActionUpdate.FunctionName == getRainProbabilityTool.FunctionName)
                    {
                        outputsToSubmit.Add(new ToolOutput(requiredActionUpdate.ToolCallId, "25%"));
                    }
                }
                else if (update is RunUpdate runUpdate)
                {
                    currentRun = runUpdate;
                }
```

We're also discussing how to clarify and simplify this pattern.

**Comment by AndrawsYaqoob01** [comment]
Can you please update the sample for the future.
