### ISSUE TITLE
System.ClientModel.ClientResultException: 'HTTP 400 (invalid_request_error: )

### ISSUE THREAD

**Issue by cjkarande** [openai/openai-dotnet#30]
I am using the following code in a .NET Standard 2.0 project within a Xamarin.Forms Solution
string _model = "gpt-3.5-turbo";
_openAI_Client = new ChatClient(model: _model, _apiKey);
ChatCompletion chatCompletion = await _openAI_Client.CompleteChatAsync(new ChatMessage[] {
     new UserChatMessage("Deep Reinforcement Learning for Finance")
});

however I am receiving the following exception on the execution of CompleteChatAsync()

System.ClientModel.ClientResultException: 'HTTP 400 (invalid_request_error: )
Parameter: messages.[0].content
Invalid value for 'content': expected a string, got null.'

**Comment by cjkarande** [comment]
@hed-openai @mjr-openai 

Anyone from the OpenAI who could have a look at this issue pls? Its a show stopper

**Comment by joseharriaga** [comment]
@trrwilson: Is this related to the issue that Chris and you were seeing with Mono?

**Comment by trrwilson** [comment]
@joseharriaga

> @trrwilson: Is this related to the issue that Chris and you were seeing with Mono?

Almost certainly the same issue, yes. There's an oddity with how serialization covariance is handled on Mono with `System.ClientModel`'s use of `ModelReaderWriter` on `IJsonModel<T>` when there's an abstract base type; in this case, the message is being written as `IJsonModel<ChatMessage>` (which has no "content" to speak of) instead of the intended derived instance type of `UserChatMessage`.

The problem is well understood, but we should consider expediting the workaround (of using virtual methods for these abstract serialization paths) in the interim.

**Comment by rudetrue** [comment]
Experiencing this as well. Let me know if I can try/test anything to work towards a fix.

**Comment by MoienTajik** [comment]
Same issue here on Blazor WASM.

**Comment by trrwilson** [comment]
To update; we've filed an issue with the .NET runtime team (thanks to @chschrae for investigating) to track the full fix for the underlying issue causing this problem:

https://github.com/dotnet/runtime/issues/103365

We're evaluating a mitigation option to unblock mono/wasm/etc. in the interim.

**Comment by cjkarande** [comment]
@trrwilson, thanks a ton for the fix, it indeed was an issue with the generic interface across different runtimes.
The issue is now resolved in the latest (2.0.0-beta.5) Nuget update. 

Appreciate the team's prompt intervention
