### ISSUE TITLE
GetAssistantAsync does not return a useful value

### ISSUE THREAD

**Issue by dspear** [openai/openai-dotnet#62]
AssistantClient.GetAssistantAsync only returns a `ClientResult`, not a `ClientResult<Assistant>`. Also, it should take a CancellationToken optional parameter, rather than just a RequestOptions optional parameter.

**Comment by KrzysztofCwalina** [comment]
I see the following overload that returns `ClirntResult<Assitant>` and accepts a cancellation token: ```public virtual AsyncPageableCollection<Assistant> GetAssistantsAsync(ListOrder? resultOrder = null, CancellationToken cancellationToken = default);```

**Comment by dspear** [comment]
Yes, there is that, but that lists all of the Assistants you have. There's another function, GetAssistant, that takes a string ID for the assistant, and only returns info about that one Assistant. That's the one that doesn't return the typed result or take a CancellationToken.

**Comment by trrwilson** [comment]
This method is present, though currently still lacking the optional `CancellationToken` parameter:

https://github.com/openai/openai-dotnet/blob/aca190004662e5818fa21f22e09866398050ce86/src/Generated/AssistantClient.cs#L35

E.g. this code compiles:
```csharp
AssistantClient client = new();
Assistant assistant = client.GetAssistant("existing-assistant-id");
```

...but *will not yet* compile if providing a `CancellationToken`.

@KrzysztofCwalina -- this was one of a few methods that didn't need any customization from the generated code, and thus it missed the pass over the methods under `/src/Custom` (since it only appeared in `/src/Generated`. I'll do a refresh to ensure we catch these remaining methods.

**Comment by KrzysztofCwalina** [comment]
fixed

**Comment by dspear** [comment]
@KrzysztofCwalina I checked this in the Beta.6 release, and this function is unchanged. It still does not take a CancellationToken parameter.

**Comment by trrwilson** [comment]
Thanks, @dspear -- yes, #70 is still pending and this should remain open until that's merged.

**Comment by rudetrue** [comment]
No sure if I'm using it wrong, but both `GetAssistant()` and `GetAssistantAsync()` never return for me. The tests seem to just use mock objects (I could be missing something though). I'm worried they don't work in their current form. I also tried using https://github.com/openai/openai-dotnet/pull/70 but had the same issue
