### ISSUE TITLE
Allow ApiKey to be optional in the OpenAIClient constructor.

### ISSUE THREAD

**Issue by RogerBarreto** [openai/openai-dotnet#90]
This will allow the OpenAIClient be used against custom OpenAI Gateways that intercept and inject the apikey, in the pipeline without having to provide a fake key on the caller code.

This also allows the client to be used against other OpenAI compatible endpoints that don't require ApiKey to be sent in the header.

https://github.com/openai/openai-dotnet/blob/0b97311f58dfb28bd883d990f68d548da040a807/src/Custom/OpenAIClient.cs#L58

Consider not having an empty check or allow us to use a `NullCredential.Instance` in the `System.ClientModel` package.

https://github.com/Azure/azure-sdk-for-net/blob/d1cac0ba5673ddcb999846d560c13f71f7b259fe/sdk/core/System.ClientModel/src/Convenience/ApiKeyCredential.cs#L64
![image](https://github.com/openai/openai-dotnet/assets/19890735/98cd4c89-616e-4238-8da7-bcf75466adc7)

**Comment by joseharriaga** [comment]
Thank you for reaching out, @RogerBarreto ! I agree that there are a few use cases where being able to provide an API key at a later point in time after client instantiation is useful. However, because these use cases are more niche, we would rather not compromise the clarity of the primary use case to try to make the niche use cases a little more convenient. With this in mind and also considering that the niche use cases are not blocked, we would rather not make this change.
